# book-print.pdf: オフセット用PDF（グレースケール画像、印刷用リンクなし、トンボあり、デフォルトオフ）

inherit: ["config.yml"]

bookname: book-print

pdfmaker:
  # coverimage: tobira.pdf
  texdocumentclass: ["thinkit-books", "tombo, pdf:kanjimap=release, cameraready=print, backmatter:break-before=page,"]
