# book.epub: 電子書籍用EPUB（カラー画像）, book.pdf: プレビュー電子書籍用PDF（カラー画像、閲覧用リンクあり、仕上がりサイズ）

# simple sample of config.yml
review_version: 2.0

debug: true

## inherited configuratons

# inherit: ["config-default.yml"]


## Book Metadata

bookname: book
language: ja
booktitle: ★★★書名★★★（Think IT Books）
aut: ["★★★著者名★★★"]
# cov: ["Masayoshi Takahashi"]
# ill: ["Masayoshi Takahashi"]
# trl: null
# edt: null
pbl: "株式会社インプレス"
# prt: "Re:VIEW Printing inc."
date: 201★-★★-★★
history: [["201★-★★-★★"]]
rights: (C) 2016 ★★★権利者名★★★, all rights reserved.
description: template config.yml file for Think IT Books series
urnid: urn:uid:https://thinkit.co.jp/tibooks
# isbn: null

## Book Structure

toclevel: 3
secnolevel: 2
direction: "ltr"

## Extra Pages

cover: null
coverimage: cover.jpg
# titlepage: null
# titlefile: null
# originaltitlefile: null
# creditfile: null
colophon: null
# backcover: null
# profile: null
# profiletitle: "About Authors"
# advfile: null

## Syntax Highlighting

highlight:
  html: "rouge"
#  latex: "listings"

## for HTML

htmlext: html
stylesheet: ["style.css"]

## for EPUB

epubmaker:
  # coverimage: tobira-1.png
  toc: true
  htmlext: xhtml
  cover_linear: true
  externallink: true
  imgmath: true

## for PDFMaker

pdfmaker:
  coverimage: cover.pdf
  # coverimage: tobira-1.pdf
  texdocumentclass: ["thinkit-books", "pdf:kanjimap=preview, cameraready=pdf, backmatter:break-before=page,"]
  #   hanmen, % draft,
  #   % hanmengrid,
  #   % tombo, % mentuke,
  #   % showremark,
  #   cameraready=pdf,%default: print; available: preview,print,pdf
  #   % paper=b5var+3.17mm,%default: b5var; available: b5var{,+3mm,+3.17mm,+4mm}
  #   %
  #   % toc:break-before=page,%default: right
  #   % backmatter:break-before=page,%default: right
  toc: true
  makeindex: true
  # makeindex_dic: book_project.dic
  # makeindex_sty: book_project.ist
  makeindex_mecab: null
  texcommand: uplatex
  dvioptions: "-d 5 -z 3"
  hook_beforetexcompile: ./hook_beforetex.rb
  # hook_aftertexcompile: ./hook_aftertex.rb
  ## end of pdfmaker
