# book-sp.pdf: 京葉SPおよびAmazonPOD用PDF（グレースケール画像、印刷用リンクなし、仕上がりサイズ）

inherit: ["config.yml"]

bookname: book-sp

pdfmaker:
  # coverimage: tobira.pdf
  texdocumentclass: ["thinkit-books", "pdf:kanjimap=release, cameraready=print, backmatter:break-before=page,"]
